apiVersion: v1
kind: Service
metadata:
  name: esd-customer-frontend
  labels:
    app: esd-customer-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5500
      protocol: TCP
      name: http
  selector:
    app: esd-customer-frontend
