services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - NODE_ENV=production
      - DEPLOYMENT_ENVIRONMENT=docker
    env_file:
      - .env
    networks:
      - kong-net
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - NODE_ENV=production
      - DEPLOYMENT_ENVIRONMENT=docker
    env_file:
      - .env
    networks:
      - kong-net

  queue-listener:
    build:
      context: .
      dockerfile: apps/queue-listener/Dockerfile
    environment:
      - NODE_ENV=production
      - DEPLOYMENT_ENVIRONMENT=docker
    env_file:
      - .env
    networks:
      - kong-net

  kong:
    image: kong:3.5
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    networks:
      - kong-net

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    env_file:
      - .env
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
