name: esd

services:
  customer-frontend:
    build:
      context: .
      dockerfile: apps/customer-frontend/Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DEPLOYMENT_ENVIRONMENT=docker
    env_file:
      - service-env/.env
    ports:
      - "5050:5050"
    networks:
      - app-net
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DEPLOYMENT_ENVIRONMENT=docker
    env_file:
      - service-env/.env
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
