packages:
  - "apps/*"
  - "packages/*"
  - "databases/*"

catalog:
  eslint: ^9.9.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  zod: ^3.23.8
  prisma: ^6.2.1
  "@prisma/client": ^6.2.1
  "@t3-oss/env-core": ^0.11.1
