apiVersion: v1
kind: Service
metadata:
  name: esd-admin-frontend
  labels:
    app: esd-admin-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4400
      protocol: TCP
      name: http
  selector:
    app: esd-admin-frontend
