apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: esdproject.azurecr.io/esd-admin-frontend:latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/darkliyznyanlin910/esd-2425T2.git
    targetRevision: HEAD
    path: kubernetes/frontend/admin/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true