apiVersion: v1
kind: Service
metadata:
  name: esd-chatbot-backend
  labels:
    app: esd-chatbot-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app: esd-chatbot-backend
