apiVersion: apps/v1
kind: Deployment
metadata:
  name: esd-auth
  labels:
    app: esd-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esd-auth
  template:
    metadata:
      labels:
        app: esd-auth
    spec:
      containers:
        - name: esd-auth
          image: esdproject.azurecr.io/esd-auth@sha256:995d5947b5a5a3dd458bff2710333975b1d0b5a8faf7de8db950f0975248791f
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-superuser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-superuser
            - name: AUTH_POSTGRES_URL
              value: "postgresql://$(PGUSER):$(PGPASSWORD)@postgres-rw.default.svc.cluster.local:5432/auth_database"
            - name: AUTH_POSTGRES_READ_REPLICA_URLS
              value: "postgresql://$(PGUSER):$(PGPASSWORD)@postgres-r.default.svc.cluster.local:5432/auth_database"
            - name: DRIVER_POSTGRES_URL
              value: "postgresql://$(PGUSER):$(PGPASSWORD)@postgres-rw.default.svc.cluster.local:5432/driver_database"
            - name: DRIVER_POSTGRES_READ_REPLICA_URLS
              value: "postgresql://$(PGUSER):$(PGPASSWORD)@postgres-r.default.svc.cluster.local:5432/driver_database"
            - name: INVOICE_POSTGRES_URL
              value: "postgresql://$(PGUSER):$(PGPASSWORD)@postgres-rw.default.svc.cluster.local:5432/invoice_database"
            - name: INVOICE_POSTGRES_READ_REPLICA_URLS
              value: "postgresql://$(PGUSER):$(PGPASSWORD)@postgres-r.default.svc.cluster.local:5432/invoice_database"
            - name: ORDER_POSTGRES_URL
              value: "postgresql://$(PGUSER):$(PGPASSWORD)@postgres-rw.default.svc.cluster.local:5432/order_database"
            - name: ORDER_POSTGRES_READ_REPLICA_URLS
              value: "postgresql://$(PGUSER):$(PGPASSWORD)@postgres-r.default.svc.cluster.local:5432/order_database"
          envFrom:
            - secretRef:
                name: app-environment
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: acr-secret
