apiVersion: apps/v1
kind: Deployment
metadata:
  name: esd-notification
  labels:
    app: esd-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esd-notification
  template:
    metadata:
      labels:
        app: esd-notification
    spec:
      containers:
        - name: esd-notification
          image: esd-notification:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
          envFrom:
            - secretRef:
                name: app-environment
            - configMapRef:
                name: database-connection-strings
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
