apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-kong-config
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
data:
  kong.yml: |
{{ .Files.Get "kong.yml" | indent 4 }} 