apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    # initdb:
    #   database: app
    #   owner: app
    #   postInitSQL:
    #     - ALTER USER "app" WITH CREATEDB;
    #     - CREATE DATABASE auth_database;
    #     - CREATE DATABASE order_database;
    #     - CREATE DATABASE driver_database;
    #     - CREATE DATABASE invoice_database;
    recovery:
      source: cluster-backup

  enableSuperuserAccess: true # By default superuser access is not created on cluster bootstrap
  imageName: ghcr.io/cloudnative-pg/postgresql:13.20-8
  instances: 1
  postgresql:
    parameters: # postgresql paramaters
      auto_explain.log_min_duration: 500ms
      checkpoint_completion_target: "0.9"
      default_statistics_target: "100"
      effective_cache_size: 1536MB
      effective_io_concurrency: "200"
      log_min_duration_statement: 20ms
      maintenance_work_mem: 128MB
      max_connections: "300"
      max_wal_size: 8GB
      min_wal_size: 2GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      random_page_cost: "1.1"
      shared_buffers: 512MB
      wal_buffers: 16MB
      work_mem: 30MB
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: https://tfstate20250430.blob.core.windows.net/cnpg
      azureCredentials:
        connectionString:
          name: azure-creds
          key: AZURE_STORAGE_CONNECTION_STRING
    retentionPolicy: "30d"
  externalClusters:
    - name: cluster-backup
      barmanObjectStore:
        destinationPath: https://tfstate20250430.blob.core.windows.net/cnpg
        azureCredentials:
          storageAccount:
            name: azure-creds
            key: AZURE_STORAGE_ACCOUNT
          storageKey:
            name: azure-creds
            key: AZURE_STORAGE_KEY
        wal:
          maxParallel: 8
  monitoring:
    enablePodMonitor: true
