apiVersion: v1
kind: Service
metadata:
  name: temporal-service
  labels:
    app: temporal-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: temporal-ui
  selector:
    app: temporal-service
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  labels:
    app: temporal
spec:
  type: ClusterIP
  ports:
    - port: 7233
      targetPort: 7233
      protocol: TCP
      name: temporal
  selector:
    app: temporal
