apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  labels:
    app: temporal-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-service
  template:
    metadata:
      labels:
        app: temporal-service
    spec:
      containers:
      - name: temporal-ui
        image: temporalio/ui:2.31.2
        ports:
        - containerPort: 8080
        env:
          - name: TEMPORAL_ADDRESS
            value: "temporal:7233"
          - name: TEMPORAL_CORS_ORIGINS
            value: "https://temporal.jknl.dev"
          - name: TEMPORAL_AUTH_ENABLED
            value: "true"
          - name: TEMPORAL_AUTH_TYPE
            valueFrom:
              secretKeyRef:
                name: temporal-auth
                key: TEMPORAL_AUTH_TYPE
          - name: TEMPORAL_AUTH_PROVIDER_URL
            valueFrom:
              secretKeyRef:
                name: temporal-auth
                key: TEMPORAL_AUTH_PROVIDER_URL
          - name: TEMPORAL_AUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: temporal-auth
                key: TEMPORAL_AUTH_CLIENT_ID
          - name: TEMPORAL_AUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: temporal-auth
                key: TEMPORAL_AUTH_CLIENT_SECRET
          - name: TEMPORAL_AUTH_CALLBACK_URL
            valueFrom:
              secretKeyRef:
                name: temporal-auth
                key: TEMPORAL_AUTH_CALLBACK_URL
          - name: TEMPORAL_AUTH_SCOPES
            valueFrom:
              secretKeyRef:
                name: temporal-auth
                key: TEMPORAL_AUTH_SCOPES
        resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
