global:
  environment: local

kong:
  proxy:
    type: NodePort
    http:
      nodePort: 31000
    enabled: true
  ingressController:
    enabled: true
  env:
    database: "off"
  dblessConfig:
    configMap: esd-kong-config

web:
  name: web
  replicaCount: 1
  image:
    repository: web
    tag: latest
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  env:
    - name: NODE_ENV
      value: production
    - name: DEPLOYMENT_ENVIRONMENT
      value: kubernetes

api:
  name: api
  replicaCount: 1
  image:
    repository: api
    tag: latest
  service:
    type: ClusterIP
    port: 80
    targetPort: 3001
  env:
    - name: NODE_ENV
      value: production
    - name: DEPLOYMENT_ENVIRONMENT
      value: kubernetes

auth:
  name: auth
  replicaCount: 1
  image:
    repository: auth
    tag: latest
  service:
    type: ClusterIP
    port: 80
    targetPort: 3002
  env:
    - name: NODE_ENV
      value: production
    - name: DEPLOYMENT_ENVIRONMENT
      value: kubernetes
