global:
  environment: local

kong:
  proxy:
    type: NodePort
    http:
      nodePort: 31001
    enabled: true
  ingressController:
    enabled: true
  env:
    database: "off"
  dblessConfig:
    configMap: esd-kong-config

# Add the missing temporal postgres credentials
temporal:
  postgres:
    user: "temporal"
    password: "temporal"

# web:
#   name: esd-web
#   replicaCount: 1
#   image:
#     repository: esd-web
#     tag: latest
#     pullPolicy: Never
#   service:
#     type: ClusterIP
#     port: 80
#     targetPort: 3000
#   env:
#     - name: NODE_ENV
#       value: production
#     - name: DEPLOYMENT_ENVIRONMENT
#       value: kubernetes

api:
  name: esd-api
  replicaCount: 1
  image:
    repository: esd-api
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 80
    targetPort: 3001
  env:
    - name: NODE_ENV
      value: production
    - name: DEPLOYMENT_ENVIRONMENT
      value: kubernetes
# auth:
#   name: esd-auth
#   replicaCount: 1
#   image:
#     repository: esd-auth
#     tag: latest
#     pullPolicy: Never
#   service:
#     type: ClusterIP
#     port: 80
#     targetPort: 3002
#   env:
#     - name: NODE_ENV
#       value: production
#     - name: DEPLOYMENT_ENVIRONMENT
#       value: kubernetes
