global:
  environment: local
  commonEnv: {}

nginx:
  replicaCount: 1
  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

auth:
  name: esd-auth
  replicaCount: 1
  image:
    repository: esd-auth
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 80
    targetPort: 3002

customer-frontend:
  name: esd-customer-frontend
  replicaCount: 1
  image:
    repository: esd-customer-frontend
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 80
    targetPort: 5050
