apiVersion: v1
kind: Service
metadata:
  name: esd-invoice
  labels:
    app: esd-invoice
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3007
      protocol: TCP
      name: http
  selector:
    app: esd-invoice
