apiVersion: apps/v1
kind: Deployment
metadata:
  name: esd-invoice
  labels:
    app: esd-invoice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esd-invoice
  template:
    metadata:
      labels:
        app: esd-invoice
    spec:
      containers:
        - name: esd-invoice
          image: esd-invoice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3007
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-app
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-app
          envFrom:
            - secretRef:
                name: app-environment
            - configMapRef:
                name: database-connection-strings
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
