apiVersion: v1
kind: Service
metadata:
  name: esd-driver
  labels:
    app: esd-driver
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3006
      protocol: TCP
      name: http
  selector:
    app: esd-driver
