apiVersion: apps/v1
kind: Deployment
metadata:
  name: esd-driver
  labels:
    app: esd-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esd-driver
  template:
    metadata:
      labels:
        app: esd-driver
    spec:
      containers:
        - name: esd-driver
          image: esd-driver:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3006
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
