apiVersion: v1
kind: Service
metadata:
  name: esd-auth
  labels:
    app: esd-auth
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    app: esd-auth
