apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/darkliyznyanlin910/esd-2425T2.git
    targetRevision: HEAD
    path: kubernetes/backend/order/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true