apiVersion: v1
kind: Service
metadata:
  name: esd-order
  labels:
    app: esd-order
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3005
      protocol: TCP
      name: http
  selector:
    app: esd-order
